# Generated by Django 2.2.3 on 2019-07-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入这本书的语言 (例如： 英语, 法语, 中文 等。)', max_length=200)),
            ],
        ),
    ]
